name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        include:
          - php: "8.1"
          - php: "8.0"
          - php: "7.4"
          - php: "7.3"

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer

#     - name: Validate composer.json and composer.lock
#       run: composer validate --strict

#     - name: Cache Composer packages
#       id: composer-cache
#       uses: actions/cache@v3
#       with:
#         path: vendor
#         key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-php-

    
    - name: Install dependencies
      run: composer install

    # - name: PHPStan
    #   run: vendor/bin/phpstan analyse -c phpstan.neon src/
    
    - name: atoum
      run: vendor/bin/atoum -d tests